// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrvpqcdjekjbugbadvqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhydnBxY2RqZWtqYnVnYmFkdnFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MDg2MjUsImV4cCI6MjA3MzA4NDYyNX0.-tFang4y0_qE4md-GP8BblYzYHLKlTBCREjIJIKWnzk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});